# Generated by Django 4.0.5 on 2022-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='face_shot',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
