# Generated by Django 4.0.5 on 2022-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup_face_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('enroll_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('face_shot', models.ImageField(blank=True, upload_to='profile_images')),
                ('date', models.DateField()),
            ],
        ),
    ]
